### ISSUE TITLE
Use `test-` instead of `test_`

### ISSUE THREAD

**Issue by GegznaV** [bryanhanson/roxut#2]
According to `testthat` recommendations, test files should go to `test-` (with a hyphen) directory and `roxut` creates `test_` (with an underscore). Can we stick to the `testthat` standard?

**Comment by bryanhanson** [comment]
Thanks.  Fixed in https://github.com/bryanhanson/roxut/commit/32d3fe6841f88b91ccaca88960b9ea944b4ed02c  Also found a test condition that was overlooked.
