### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by cbeleites** [bryanhanson/roxut#3]
I propose to put a comment at the beginning of each test code block that tells the line number within the file the `@tests` came 
from.

e.g. `tests <- sub("\\[.*/([^/]+\\.R:[0-9]+)\\](.*)", "# \\1\n\\2", results[[framework]])`

In https://github.com/bryanhanson/roxut/blob/master/R/roclet_output.roclet_tests.R l. 59

(not sure whether the `\n` is actually needed/good to have)

**Comment by bryanhanson** [comment]
Thanks. Implemented in https://github.com/bryanhanson/roxut/commit/37e972acdfdfb9f032d73c16ad10cee013a8239e with minor formatting changes.
