### ISSUE TITLE
Allow order test files

### ISSUE THREAD

**Issue by GegznaV** [bryanhanson/roxut#4]
Control order of files (for parallel testing, slowest files should be first; `testthat` runs tests in alphabetical order, so ability to add file name {suffix}, e.g., `test-{suffix}-file_name.R` would be an advantage.

Test that also has another mechanism to prioritize files, so this is not very urgent.

**Comment by bryanhanson** [comment]
So the other mechanism is this one I think `Config/testthat/start-first: watcher, parallel*` which is straight-forward.

I don't see any way that roxut can know which files the user wants to run first, unless that information is incorporated into the original file names like `01-function-test.R` which would then become `test-01-function-test.R` and be processed first (depending upon the locale sorting maybe, does `01` run before `1`?).
