### ISSUE TITLE
Use path relative to package's main dir

### ISSUE THREAD

**Issue by GegznaV** [bryanhanson/roxut#6]
I'd prefer if in the second line of `test-*.R` files generated by `roxut`, path, relative to package's main directory, was used instead of an absolute path.

**Comment by bryanhanson** [comment]
On Mac OS at least one only gets the file name itself, because `basename` is used.  Looking at `?basename` it may behave differently on Windows.

**Comment by bryanhanson** [comment]
Digging a little deeper, I don't completely understand what `?basename` and `?path.expand` are saying relative to Windows file system.  You might have to try it at the console to see what is actually returned.

**Comment by GegznaV** [comment]
It is OK to use `basename()` to return file name only.

**Comment by bryanhanson** [comment]
Fixed via https://github.com/bryanhanson/roxut/commit/350a49e69b639af3243fdade70cae36c7fdce5c2 Thanks to VG for testing on Windows 10.
